// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxepfidqpwcvuvsqwilf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14ZXBmaWRxcHdjdnV2c3F3aWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjA2MzcsImV4cCI6MjA3MTk5NjYzN30.Ytqs6n4vCEMYC9FzSyZc7aZMpq-en5D_Xe4n6dlTCq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});